services:
  - type: web
    name: intelligent-resume-screening
    runtime: python3
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn --bind 0.0.0.0:$PORT prolog_resume_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 1 